server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:mysql://82.156.175.33:3306/scientific_statistic_dev?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 248614740
    pool:
      enabled: true
      max-size: 50
      initial-size: 30
      validation-query: select 1
      max-idle-time: 300m
      max-acquire-time: 3s
      max-create-connection-time: 5s


